### ISSUE TITLE
Failure to update occurrence records, when supplied in an extension

### ISSUE THREAD

**Issue by kbraak** [gbif/crawler#1]
### Description of bug

When recrawling datasets with occurrence records supplied in an extension, occurrence records aren't being updated despite having changed at source. 

I suspect the problem is related to how the crawler checks if two records are identical, critical in deciding whether to update the record or not. More specifically, I suspect that the equality check only takes into consideration the core record, which explains why changes to the occurrence record (supplied in an extension) aren't detected. 

Note this issue was originally reported by @dschigel on behalf of Roman and confirmed by @jlegind.

### Supporting info
Version 1.4 of the following checklist dataset with associated occurrences was republished on 2017-02-28 via IPT: http://ipt.zin.ru:8080/ipt/resource?r=zin_cosmopterigidae This version was crawled successfully by GBIF on 2017-02-28: http://www.gbif.org/dataset/8d431c96-9e2f-4249-8b0a-d875e3273908 The occurrence records' field 'references' was changed in version 1.4, however, this change was never picked up by GBIF. As an example, see this [record](http://www.gbif.org/occurrence/1420234163/verbatim):
* references (version 1.3)=http://www.zin.ru/Collections/Coleoptera/specimen_en.html?Catalog_UID=1309911838213053
* references (version 1.4)=http://www.zin.ru/Collections/Lepidoptera/specimen_en.html?Catalog_UID=1309911838213053

**Comment by mdoering** [comment]
Plazi just reported a similar issue:
-----
This seems not to work: See eg http://www.gbif.org/species/1321631 that has been uploaded without extraction of oberservation records, and couple of hours later we made changes adding occurrences, but I can’t see them on GBIF

**Comment by cgendreau** [comment]
The crawl was not started automatically because of:
`org.gbif.api.exception.ServiceUnavailableException: Error communicating with ZooKeeper, getting status for 8d431c96-9e2f-4249-8b0a-d875e3273908`

If we start it manually:
`Successfully extracted [0] records out of DwC-A for dataset [8d431c96-9e2f-4249-8b0a-d875e3273908] `

Which means the the Occurrence extension was detected but not read properly.

**Comment by cgendreau** [comment]
Sending the archive to the [gbif-data-validator](https://github.com/gbif/gbif-data-validator) (in development):

`Record referential integrity violation : 50`

`taxon.txt` uses id as UUID (e.g. f8c19b99-f7b1-4aa3-b6ee-73f372002836) but `occurrence.txt` file points to `id` like `1309911838153326`. Therefore, the link between the 2 files can not be resolved which means occurrences are skipped.

**Comment by mdoering** [comment]
The Plazi problem is related to [ZooKeeper crawling problems](https://github.com/gbif/crawler/issues/2), the original Russian problem dues to bad referential integrity in the DwC-A

**Comment by mdoering** [comment]
@kbraak sth for the helpdesk to continue with

**Comment by kbraak** [comment]
Thanks @mdoering and @cgendreau I have reported the referential integrity problem to the publisher.
