### ISSUE TITLE
BioCASE dataset has same crawl ID spread across different dates

### ISSUE THREAD

**Issue by jlegind** [gbif/crawler#28]
The German dataset Flora von Deutschland (Phanerogamen) https://www.gbif.org/dataset/e6fab7b3-c733-40b9-8df3-2a03e49532c1 has the crawlID 87 attached to 12 different crawl dates from 2016 to 2019:

![flora](https://user-images.githubusercontent.com/5330066/64688235-3323b980-d48c-11e9-8eb9-057024f29574.jpg)

I don't know whats going on. Help appreciated.

HiveQL:

    SELECT to_date(from_unixtime(cast(fragmentcreated/1000 as INT))), crawlid, count(*) FROM occurrence_hdfs
    WHERE datasetkey = 'e6fab7b3-c733-40b9-8df3-2a03e49532c1' GROUP BY to_date(from_unixtime(cast(fragmentcreated/1000 as INT))), crawlid

**Comment by jlegind** [comment]
Here is another example with Collections and observation data National Museum of Natural History Luxembourg:


    SELECT to_date(from_unixtime(cast(fragmentcreated/1000 as INT))), crawlid, count(*) FROM occurrence_hdfs
    WHERE datasetkey = '962f59bc-f762-11e1-a439-00145eb45e9a' GROUP BY to_date(from_unixtime(cast(fragmentcreated/1000 as INT))), crawlid

**Comment by MattBlissett** [comment]
With pipelines, this is no longer a relevant issue.
