### ISSUE TITLE
Auto-crawl script never recrawls datasets of type sampling-event and metadata

### ISSUE THREAD

**Issue by kbraak** [gbif/crawler#6]
@jlegind uses an auto-crawl script to automatically recrawl all registered datasets [every 7 days](https://github.com/gbif/ipt/wiki/FAQ.wiki#3-how-often-does-gbif-reindex-my-dataset). I suspect that the auto-crawl script never attempts to recrawl datasets of type SAMPLING_EVENT and METADATA. The script was likely written prior to the existence of the SAMPLING_EVENT type. 

Supporting evidence showing various datasets of these two types never recrawled is shown below:

| dataset | type | lastPublished | lastCrawled |
| --- | --- | --- | --- |
| [Saproxylic inse..](https://registry.gbif.org/web/#/dataset/04930329-93ce-4f80-8d67-423a526a736b) | SAMPLING_EVENT | 22/06/16 | 23/06/16 |
| [Priority effects...](https://registry.gbif.org/web/#/dataset/3b778b3e-c784-4df6-bd89-364e0ab503ed) | SAMPLING_EVENT | 01/11/16 | 01/11/16 |
| [Redlisted bee...](https://registry.gbif.org/web/#/dataset/c6fe2d03-eeb2-4af7-bd7f-f2e5bfef02b3) | SAMPLING_EVENT | 04/11/16 | 04/11/16 |
| [Predicted abun...](https://registry.gbif.org/web/#/dataset/b7d7acc7-bf3e-4ccb-a96f-05c638828915) | METADATA | 12/08/15 | NEVER CRAWLED |
| [Ocean acid...](https://registry.gbif.org/web/#/dataset/943fd513-dbe9-4b0e-b7b1-c5520e402b4f) | METADATA | 24/09/15 | NEVER CRAWLED |
| [Effects of veg...](https://registry.gbif.org/web/#/dataset/c5fe763f-6851-4610-bdc3-67143540be67) | METADATA | 27/02/17 | NEVER CRAWLED |
| [Lichens from ...](https://registry.gbif.org/web/#/dataset/cf999616-58f0-43af-8dba-164c0323f19d) | METADATA | 27/02/17 | NEVER CRAWLED |

Currently there is a total of 85 sampling-event datasets and 45 metadata-only datasets that aren't recrawled due to this error.

**Comment by MattBlissett** [comment]
This was fixed in https://github.com/gbif/gbif-configuration/commit/b778ace7a109516548097e876a0172078fda1124 and https://github.com/gbif/gbif-configuration/commit/e8f72b2b882d15a5d79b6141181d19c4f0993015
