### ISSUE TITLE
EML endpoints ignored by CrawlerCoordinatorService

### ISSUE THREAD

**Issue by cgendreau** [gbif/crawler#7]
Datasets of type `METADATA` with a single EML endpoint will never be crawled.
Since `EndpointType.EML` is not part of the `EndpointPriorityComparator` the metadata only datasets will always produce a
`No eligible endpoints for dataset [72928c80-aeaf-4778-b414-3a13f2ad41b1]`.

Linked to https://github.com/gbif/crawler/issues/3

**Comment by kbraak** [comment]
@cgendreau @fmendezh I thought crawling metadata-only datasets was put into production, wasn't it?

I flagged https://github.com/gbif/portal-feedback/issues/589 yesterday, indicating the contrary but maybe the root is that crawling is down or malfunctioning in general. 

Your help updating the progress on this issue and crawling in general would be much appreciated by me and @jlegind - thanks.

**Comment by MattBlissett** [comment]
With https://github.com/gbif/occurrence/commit/edfff6f9aedded6a28b5e2b444d0e3223381f477, metadata-only endpoints are now crawled when they're created, and with the commit above, in the regular schedule.
